Pixel perfect
GuyAvraham/Checkout-page-sdk pull request #10
Opened 2022-02-15 13:49 UTC by AvnerGuyAvrahamCom

2022-02-15 14:07 UTC, ValentineGuyAvrahamCom commented on src/Components/CheckoutModal/CheckoutModalBody.tsx
> +const BoxContainerStyle = (isMobile: boolean) => {
fix like we do before I send u an example

2022-02-15 14:16 UTC, ValentineGuyAvrahamCom commented on src/Components/CheckoutModal/OrderSummary/GeneralDetails.tsx
> +        {currencyFigure(currency, value)}
I think u can replace it with `{value !== 0 && currency}`

2022-02-15 16:33 UTC, ValentineGuyAvrahamCom commented on src/Components/CheckoutModal/Sections/Shipping/FormInput.tsx
> +  w?: string | undefined;
if u have `?:` u dont need this `| undefined`

2022-02-15 16:34 UTC, ValentineGuyAvrahamCom commented on src/Components/CheckoutModal/Sections/Shipping/index.tsx
> +          <Text fontSize="11px">APARTMENT, BUILDING, FLOOR</Text>
move this text to messages file

2022-02-15 18:49 UTC, AvnerGuyAvrahamCom commented on src/Components/CheckoutModal/OrderSummary/GeneralDetails.tsx
> +        {currencyFigure(currency, value)}
done

2022-02-15 20:53 UTC, AvnerGuyAvrahamCom commented on src/Components/CheckoutModal/CheckoutModalBody.tsx
> +const BoxContainerStyle = (isMobile: boolean) => {
done

2022-02-15 21:32 UTC, AvnerGuyAvrahamCom commented on src/Components/CheckoutModal/OrderSummary/index.tsx
>    borderRightRadius: { md: 'md', base: undefined },
done

2022-02-15 21:32 UTC, AvnerGuyAvrahamCom commented on src/Components/CheckoutModal/Sections/Shipping/FormInput.tsx
> +  w?: string | undefined;
done

2022-02-15 21:34 UTC, AvnerGuyAvrahamCom commented on src/Components/CheckoutModal/Sections/Shipping/index.tsx
> +          <Text fontSize="11px">APARTMENT, BUILDING, FLOOR</Text>
done

2022-02-16 09:22 UTC, ValentineGuyAvrahamCom approved these changes

2022-02-16 09:38 UTC, ValentineGuyAvrahamCom requested changes

2022-02-16 09:38 UTC, ValentineGuyAvrahamCom commented on src/Components/CheckoutModal/ProgressBar/ControlButton.tsx
> +  func: () => void;
please give correct name of function

2022-02-16 09:38 UTC, ValentineGuyAvrahamCom commented on src/Components/CheckoutModal/ProgressBar/ControlButton.tsx
> +  variant: 'unstyled',
variant its not Button Style move it to button prop

2022-02-16 10:17 UTC, AvnerGuyAvrahamCom commented on src/Components/CheckoutModal/ProgressBar/ControlButton.tsx
> +  variant: 'unstyled',
done

2022-02-16 10:18 UTC, AvnerGuyAvrahamCom commented on src/Components/CheckoutModal/ProgressBar/ControlButton.tsx
> +  func: () => void;
done

2022-02-16 10:21 UTC, ValentineGuyAvrahamCom approved these changes

2022-02-16 10:26 UTC, merged